function vfdFaultCodeAnalyzer(pumpID,faultCode){
	var faultResp = ""; 
    switch (faultCode){
        case 2: faultResp = "EEPROM control";
                break;
        case 3: faultResp = "Incorrect configuration";
                break;
        case 4: faultResp = "Invalid configuration";
                break;
        case 5: faultResp = "Modbus communication interruption";
                break;
        case 6: faultResp = "Internal communication interruption with option module ";
                break;
        case 7: faultResp = "Fieldbus communication interruption";
                break;
        case 8: faultResp = "External detected error";
                break;
        case 9: faultResp = "Overcurrent";
                break;
        case 10: faultResp = "Precharge capacitor";
                break;
        case 11: faultResp = "Encoder feedback loss";
                break;
        case 12: faultResp = "Load slipping";
                break;
        case 15: faultResp = "Input Overheating";
                break;
        case 16: faultResp = "Drive overheating";
                break;
        case 17: faultResp = "Motor overload";
                break;
        case 18: faultResp = "DC bus overvoltage";
                break;
        case 19: faultResp = "Supply mains overvoltage";
                break;
        case 20: faultResp = "Single output phase loss";
                break;
        case 21: faultResp = "Input phase loss";
                break;
        case 22: faultResp = "Supply mains undervoltage";
                break;
        case 23: faultResp = "Motor short circuit";
                break;
        case 24: faultResp = "Motor overspeed";
                break;
        case 25: faultResp = "Autotuning detected error";
                break;
        case 26: faultResp = "Internal Error 1 (Rating)";
                break;
        case 27: faultResp = "Internal Error 2 (Soft)";
                break;
        case 28: faultResp = "Internal Error 3 (Intern Comm)";
                break;
        case 29: faultResp = "Internal Error 4 (Manufacturing)";
                break;
        case 30: faultResp = "EEPROM power";
                break;
        case 32: faultResp = "Ground short circuit";
                break;
        case 33: faultResp = "Output phase loss";
                break;
        case 34: faultResp = "CANopen communication interruption";
                break;
        case 35: faultResp = "Brake control";
                break;
        case 37: faultResp = "Internal Error 7 (Init)";
                break;
        case 38: faultResp = "External error detected by Fieldbus";
                break;
        case 40: faultResp = "Internal error 8 (Switching Supply)";
                break;
        case 41: faultResp = "Brake feedback";
                break;
        case 42: faultResp = "PC communication interruption";
                break;
        case 43: faultResp = "Encoder coupling";
                break;
        case 44: faultResp = "Torque limitation error";
                break;
        case 45: faultResp = "HMI communication interruption";
                break;
        case 51: faultResp = "Internal Error 9 (Measure)";
                break;
        case 52: faultResp = "Internal Error 10 (Mains)";
                break;
        case 53: faultResp = "Internal Error 11 (Temperature)";
                break;
        case 54: faultResp = "IGBT overheating";
                break;
        case 55: faultResp = "IGBT short circuit";
                break;
        case 56: faultResp = "Motor short circuit";
                break;
        case 57: faultResp = "Torque timeout";
                break;
        case 58: faultResp = "Output contactor closed error";
                break;
        case 59: faultResp = "Output contactor opened error";
                break;
        case 60: faultResp = "Internal Error 12 (Internal current supply)";
                break;
        case 62: faultResp = "Encoder";
                break;
        case 64: faultResp = "input contactor";
                break;
        case 65: faultResp = "DB unit sh. circuit";
                break;
        case 68: faultResp = "Internal Error 6 (Option)";
                break;
        case 69: faultResp = "Internal Error 14 (CPU)";
                break;
        case 70: faultResp = "Braking resistor overload";
                break;
        case 71: faultResp = "AI3 4-20mA loss";
                break;
        case 72: faultResp = "AI4 4-20mA loss";
                break;
        case 73: faultResp = "Boards compatibility";
                break;
        case 76: faultResp = "Dynamic load detected error";
                break;
        case 77: faultResp = "Configuration transfer error";
                break;
        case 79: faultResp = "AI5 4-20 mA loss";
                break;
        case 99: faultResp = "Channel switching detected error";
                break;
        case 100: faultResp = "Process Underload";
                break;
        case 101: faultResp = "Process overload";
                break;
        case 105: faultResp = "Angle error";
                break;
        case 106: faultResp = "AI1 4-20 mA loss";
                break;
        case 107: faultResp = "Safety function detected error";
                break;
        case 112: faultResp = "AI3 thermal level error";
                break;
        case 113: faultResp = "Thermal sensor error on AI3";
                break;
        case 120: faultResp = "AI4 thermal level error";
                break;
        case 121: faultResp = "Thermal sensor error on AI4";
                break;
        case 122: faultResp = "AI5 thermal level error";
                break;
        case 123: faultResp = "Thermal sensor error on AI5";
                break;
        case 128: faultResp = "Program loading detected error";
                break;
        case 129: faultResp = "Program running detected error";
                break;
        case 142: faultResp = "Internal Error 16 (IO Module - Relay)";
                break;
        case 143: faultResp = "Internal Error 17 (IO Module - Standard)";
                break;
        case 144: faultResp = "Internal Error 0 (IPC)";
                break;
        case 146: faultResp = "Internal Error 13 (Diff Current)";
                break;
        case 148: faultResp = "Motor stall detected error";
                break;
        case 149: faultResp = "Internal Error 21 (RTC)";
                break;
        case 150: faultResp = "Embedded Ethernet communication interruption";
                break;
        case 151: faultResp = "Internal Error 15 (Flash)";
                break;
        case 152: faultResp = "Firmware Update Error";
                break;
        case 153: faultResp = "Internal Error 22 (Embedded Ethernet)";
                break;
        case 154: faultResp = "Internal Error 25 (Incompatibility CB & SW)";
                break;
        case 155: faultResp = "Internal Error 20 (option interface PCBA)";
                break;
        case 156: faultResp = "Internal Error 19 (Encoder module)";
                break;
        case 157: faultResp = "Internal Error 27 (Diagnostics CPLD)";
                break;
        case 158: faultResp = "Internal Error 23 (Module link)";
                break;
        case 159: faultResp = "AFE ShortCircuit error";
                break;
        case 160: faultResp = "AFE Bus unbalancing";
                break;
        case 161: faultResp = "Internal Error 28 (AFE)";
                break;
        case 173: faultResp = "Cabinet overheat  error";
                break;
        case 175: faultResp = "Internal Error 31 (Missing brick)";
                break;
        case 176: faultResp = "Internal Error 29 (Inverter)";
                break;
        case 177: faultResp = "Internal Error 30 (Rectifier)";
                break;
        case 179: faultResp = "AFE IGBT over-heat error";
                break;
        case 180: faultResp = "AFE contactor feedback error";
                break;
        case 181: faultResp = "Pre-settings transfer error";
                break;
        case 182: faultResp = "Circuit breaker error";
                break;
        case 184: faultResp = "DB unit open circuit";
                break;
        case 185: faultResp = "Drive overload";
                break;
        case 186: faultResp = "MultiDrive Link Error";
                break;
        case 187: faultResp = "AI1 thermal level error";
                break;
        case 188: faultResp = "Thermal sensor error on AI1";
                break;
        case 189: faultResp = "Backlash error";
                break;
        case 190: faultResp = "M/S device error";
                break;
        case 194: faultResp = "Encoder module thermal level error";
                break;
        case 195: faultResp = "Thermal sensor error on encoder module";
                break;
        case 196: faultResp = "Empty configuration";
                break;
        case 200: faultResp = "FDR Eth embedded error";
                break;
        case 201: faultResp = "FDR Eth module error";
                break;
        case 206: faultResp = "DC Bus ripple error";
                break;
        case 208: faultResp = "Idle mode exit error";
                break;
        case 209: faultResp = "Load movement error";
                break;
        default:
            watchDog.eventLog("No VFD Error");
	}
	watchDog.eventLog('VFD '+pumpID+ '::FaultCode::  '+faultCode + '::Description::  '+faultResp); 
}

module.exports.vfdFaultCodeAnalyzer=vfdFaultCodeAnalyzer;
